export const ErrorCodes = {
  MATCH_VECTOR_FAIL: 'MATCH_VECTOR_FAIL',
  MATCH_EMPTY_INPUT: 'MATCH_EMPTY_INPUT',
  REGISTER_EMAIL_EXISTS: 'REGISTER_EMAIL_EXISTS',
  REGISTER_WEAK_PASSWORD: 'REGISTER_WEAK_PASSWORD',
  RESET_INVALID_EMAIL: 'RESET_INVALID_EMAIL',
  RESET_INVALID_TOKEN: 'RESET_INVALID_TOKEN',
  RESET_EXPIRED_TOKEN: 'RESET_EXPIRED_TOKEN',
  RESET_WEAK_PASSWORD: 'RESET_WEAK_PASSWORD',
} as const;
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
